[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_title   = false
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[scrolling]
history = 12000

[font]
builtin_box_drawing = false
size                = 7.5

[font.normal]
family = "ProggyVector"
style  = "Regular"

[font.offset]
x = 0
y = -2

[colors.primary]
background = "#232323"
foreground = "#C0C5CE"

[colors.bright]
black   = "#5C5C5C"
blue    = "#6699CC"
cyan    = "#5FB3B3"
green   = "#A6BC99"
magenta = "#824F82"
red     = "#E57373"
white   = "#F3F4F5"
yellow  = "#FAC863"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.footer_bar]
background = "#C0C5CE"
foreground = "#232323"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black   = "#232323"
blue    = "#6699CC"
cyan    = "#5FB3B3"
green   = "#A6BC99"
magenta = "#824F82"
red     = "#E57373"
white   = "#C0C5CE"
yellow  = "#FAC863"

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
